version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/aiomayo/aiodl

linters:
  default: standard

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
